features:
  PER:
    description: person
    output: false
  ORG:
    description: organization
    output: false
  LOC:
    description: localization
    output: false
  MISC:
    description: miscelaneous
    output: false
  FINANCIAL_DATA:
    description: financial_data
    output: true
  MONEY:
    description: monetary_quantity
    output: true
  PROB_CURRENCY:
    description: probable_currency_amount
    output: false
  EMAIL:
    description: personal_email
    output: true
  CORP_EMAIL:
    description: corporate_email
    output: false
  ID_DOCUMENT:
    description: document_id
    output: true
  MOBILE:
    description: mobile_phone_number
    output: true
  PHONE:
    description: phone_number
    output: false
  SIGNATURE:
    description: signature
    output: true
    max_distance: 15
  CUSTOM:
    description: custom_words
    output: true

# Features analyzed by faro that will be written to the output
# together with the document metadata and final score
# TODO: how to do this better, maybe wait until we have a frontend?
scoring_output_features:
    - monetary_quantity
    - signature
    - personal_email
    - mobile_phone_number
    - financial_data
    - document_id
    - custom_words


sensitivity_list:
    - low
    - medium
    - high

sensitivity_multiple_kpis: 3

sensitivity:
    low:
        monetary_quantity:
            min: 1
            max: 6

        signature:
            min: 0
            max: 0

        personal_email:
            min: 1
            max: 2

        mobile_phone_number:
            min: 1
            max: 2

        financial_data:
            min: 0
            max: 0

        document_id:
            min: 0
            max: 0

        custom_words:
            min: 0
            max: 0

    medium:
        monetary_quantity:
            min: 6
            max: 65535

        signature:
            min: 1
            max: 2

        personal_email:
            min: 2
            max: 65535

        mobile_phone_number:
            min: 2
            max: 4

        financial_data:
            min: 0
            max: 0

        document_id:
            min: 0
            max: 0

        custom_words:
            min: 0
            max: 0

    high:
        monetary_quantity:
            min: 65535
            max: 65535

        signature:
            min: 2
            max: 65535

        personal_email:
            min: 65535
            max: 65535

        mobile_phone_number:
            min: 4
            max: 65535

        financial_data:
            min: 1
            max: 65535

        document_id:
            min: 1
            max: 65535

        custom_words:
            min: 1
            max: 65535

