regexp_config:
  CreditCard:
    word_file: keywords_creditcard_es.txt
    left_span_len: 20
    right_span_len: 0

  FinancialData:
    word_file: keywords_financialdata_es.txt
    left_span_len: 20
    right_span_len: 0

  DNI_SPAIN:
    word_file: keywords_dni_spain_es.txt
    left_span_len: 20
    right_span_len: 0

  PHONE:
    word_file: keywords_phone_es.txt
    left_span_len: 20
    right_span_len: 0

  MOBILE:
    word_file: keywords_mobile_es.txt
    left_span_len: 20
    right_span_len: 0

email_config:
  excl_file: excl_corp_email_es.txt

ner_config:
    nlp_model : es_core_news_sm

custom_config:
  word_file: keywords_custom_words_es.txt

