proximity_regexp_config:
   CreditCard:
       word_file: config/keywords_creditcard_es.txt
       span_len: 50

   FinancialData:
       word_file: config/keywords_financialdata_es.txt
       span_len: 50

   DNI_SPAIN:
       word_file: config/keywords_dni_spain_es.txt
       span_len: 50

   PHONE:
       word_file: config/keywords_phone_es.txt
       span_len: 50

   MOBILE:
       word_file: "config/keywords_mobile_es.txt"
       span_len: 50

detection:
    nlp_model : es_core_news_sm
    crf_ner_list: models/crf_professions_v1.joblib
    personal_email_detection: models/email_detector.joblib
    crf_ner_classic: "models/crf_classic_step1.joblib,models/crf_classic_step2.joblib,models/crf_classic_step3.joblib,models/crf_classic_step4.joblib,models/crf_classic_step5.joblib"
    corp_mail_list: models/corp_mail_list.txt

