#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
from utils.pattern.entrypoint_pattern_base import PluginPatternEntrypointBase

_CWD = os.path.dirname(__file__)

MANIFEST = {
    "name": "Address Bitcoin",
    "key": "FINANCIAL_DATA",
    "version": "1",
    "description": "Address Bitcoin Detection",
    "author": "Enrique and Hugo",
    "email": "enrique@telefonica.com",
    "is_lang_dependent": False,
    "info": "https://en.bitcoin.it/wiki/Invoice_address"
}


class PluginEntrypoint(PluginPatternEntrypointBase):
    """
    Address Bitcoin Plugin entrypoint class.

    """

    def __init__(self, text, lang='uk'):
        """
        Initialize pattern plugin base plus additional parameters.

        :param text: Incoming text
        :param lang: Detected language from FARO Core
        """
        super().__init__(_CWD, MANIFEST["is_lang_dependent"], MANIFEST["key"], lang, text)

    def output(self, unconsolidated_lax_dict=None, consolidated_lax_dict=None, strict_ent_dict=None,
               validate_dict=None):
        """
        Default output generation method. It can be overriden.

        :param unconsolidated_lax_dict: Detected entities by lax regex expression from pattern.lax_regexp() not validated by context.
        :param consolidated_lax_dict: Detected entities by lax regex expression from pattern.lax_regexp() validated by context.
        :param strict_ent_dict: Detected entities by strict regex expression from pattern.strict_regexp() method.
        :param validate_dict: Validated detected entities regex expression both from lax and strict from pattern.validate() method.

        :return: Output dictionary with detected entities to be returned.
        """
        return super().output(validate_dict=validate_dict)

    def run(self):
        """
        Public plugin interface. It can be overriden.

        :return: Output dictionary with detected entities. (Default output is generated by output method).
        """
        return super().run()
